steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/api-service', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/api-service']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run',
        'deploy',
        'api-service',
        '--image',
        'gcr.io/$PROJECT_ID/api-service',
        '--platform',
        'managed',
        '--region',
        'europe-west1',
        '--allow-unauthenticated',
      ]

options:
  logging: CLOUD_LOGGING_ONLY
