const primary = "#a1c4df"
const secondary = '#495263'

export const Colors = {
  light: {
    primary: primary,
    secondary: '#fff',
    accent: '#fff',
    icon: '#000',
    textPrimary: '#000',
    textSecondary: '#acacacaa',
    textDisabled: '#fff',
    textReverse: '#fff',
    background: '#fff',
    border: '#acacac5f',
    divider: '#fff',
    primaryButton: '#000',
    secondaryButton: '#fff',
    hoverButton: '#fff',
    pressButton: '#a1a1a14a',
    activeButton: '#fff',
    disabledButton: '#fff',
    error: '#fff',
    success: '#fff',
    warning: '#fff',
    gray: '#fff',
  },
  dark: {
    primary: primary,
    secondary: '#fff',
    accent: '#fff',
    icon: '#fff',
    textTitle: '#fff',
    textPrimary: '#fff',
    textSecondary: '#acacacaa',
    textDisabled: '#fff',
    textReverse: '#000',
    background: '#000',
    border: '#acacac5f',
    divider: '#fff',
    primaryButton: '#fff',
    secondaryButton: '#fff',
    hoverButton: '#fff',
    pressButton: '#a1a1a14a',
    activeButton: '#fff',
    disabledButton: '#fff',
    error: '#fff',
    success: '#fff',
    warning: '#fff',
    gray: '#fff',
  },
};
